default:
  # NOTE: options that apply to all the whitman data repos
  # are in data/config/private.yml
  # (solr_core, solr_path, solr_variables, etc)

  shortname: whitman-notebooks
  collection_desc: Notebooks for The Walt Whitman Archive
  tei_solr_xsl: collections/whitman-notebooks/scripts/solr_transform_tei.xsl
  # es_type:

development:
  # development overrides here
production:
  # production overrides here
