default:
  # NOTE: options that apply to all the whitman data repos
  # are in data/config/private.yml
  # (solr_core, solr_path, solr_variables, etc)

  shortname: whitman-notebooks
  collection_desc: Notebooks for The Walt Whitman Archive
  tei_solr_xsl: collections/whitman-notebooks/scripts/solr_transform_tei.xsl
  # es_type:

  variables_solr:
    project: The_Walt_Whitman_Archive
    site_url: https://whitmanarchive.org
    slug: whitman-notebooks
development:
  variables_solr:
    project: The_Walt_Whitman_Archive
    site_url: https://whitman-dev.unl.edu
    slug: whitman-notebooks
# production:
  # production overrides here
