default:
  shortname: whitman-notebooks
  collection: whitman-notebooks
  site_url: https://whitmanarchive.org
  solr_core: api_whitman
  # tei_solr_xsl: scripts/overrides/solr_transform_tei.xsl
  tei_html_xsl: scripts/overrides/tei_to_html.xsl

development:
  data_base: https://whitman-dev.unl.edu/media
  es_path: https://whitman-dev.unl.edu/elastic
  es_index: api_v1
  site_url: https://whitman-dev.unl.edu
  solr_path: https://whitman-dev.unl.edu/solr

  variables_solr:
    project: The_Walt_Whitman_Archive
    slug: whitman-notebooks
    site_url: https://whitman-dev.unl.edu

production:
  data_base: https://whitmanarchive.org/media
  site_url: https://whitmanarchive.org
  solr_path: https://whitman-prod.unl.edu/solr

  variables_solr:
    project: The_Walt_Whitman_Archive
    slug: whitman-notebooks
    site_url: https://whitmanarchive.org
