default:
  # NOTE: options that apply to all the whitman data repos
  # are in data/config/private.yml
  # (solr_core, solr_path, solr_variables, etc)

  shortname: whitman-notebooks
  collection: whitman
  site_url: https://whitmanarchive.org

  # TODO this collection_desc is specific to the subcategory, not the ES collection
  # collection_desc: Notebooks for The Walt Whitman Archive

  tei_solr_xsl: collections/whitman-notebooks/scripts/solr_transform_tei.xsl

  variables_solr:
    figures: false
    fw: false
    pb: false
    project: The_Walt_Whitman_Archive
    slug: whitman-notebooks
development:
  site_url: https://whitman-dev.unl.edu
  # development overrides here
production:
  # production overrides here
